In [1]:
#How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr
#Input:
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [2]:
#2.How to replace items that satisfy a condition with another value in numpy array?
#Q. Replace all odd numbers in arr with -1
#Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [3]:
#How to replace items that satisfy a condition without affecting the original array?
#Replace all odd numbers in arr with -1 without changing arr
#Input:
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#How to reshape an array?
#Convert a 1D array to a 2D array with 2 rows
#Input:
#np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.arange(10)
print(arr.reshape(2, -1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
#How to stack two arrays vertically?
#Q. Stack arrays a and b vertically
#Input
#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a, b], axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
#How to stack two arrays horizontally?
#Q. Stack the arrays a and b horizontally
#Input
#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.concatenate([a, b], axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [7]:
#How to generate custom sequences in numpy without hardcoding?
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#Input:
#a = np.array([1,2,3])
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [8]:
#How to get the common items between two python numpy arrays?
#QGet the common items between a and b
#Input:
#a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [9]:
#How to remove from one array those items that exist in another?
#From array a remove all items present in array b#Input:
#a = np.array([1,2,3,4,5])
#b = np.array([5,6,7,8,9])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


In [10]:
#How to get the positions where elements of two arrays match?
#Q. Get the positions where elements of a and b match

#Input:

#a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


In [11]:

#How to extract all numbers between a given range from a numpy array?

#Q. Get all items between 5 and 10 from a.

#Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 5  6  7  8  9 10]


In [12]:

#How to make a python function that handles scalars to work on numpy arrays?
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

#Input:
#def maxx(x, y):
 #   """Get the maximum of two items"""
  #  if x >= y:
  #      return x
  #  else:
  #      return y

#maxx(1, 5)
#> 5

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(pair_max(a, b))


[6. 7. 9. 8. 9. 7. 5.]


In [13]:
#How to swap two columns in a 2d numpy array?

#Q. Swap columns 1 and 2 in the array arr.

#arr = np.arange(9).reshape(3,3)
#arr

arr = np.arange(9).reshape(3,3)
arr
print(arr[:, [1,0,2]])

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [14]:
#How to swap two rows in a 2d numpy array?
#Q. Swap rows 1 and 2 in the array arr:

#arr = np.arange(9).reshape(3,3)
#arr
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [15]:
#How to reverse the rows of a 2D array?

#Q. Reverse the rows of a 2D array arr.

# Input
#arr = np.arange(9).reshape(3,3)
import numpy as np 
arr = np.arange(9).reshape(3,3)
print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [16]:
#How to reverse the columns of a 2D array?

#Q. Reverse the columns of a 2D array arr.

# Input
#arr = np.arange(9).reshape(3,3)

arr = np.arange(9).reshape(3,3)
print(arr[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [17]:
#How to create a 2D array containing random floats between 5 and 10?

#Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Inputimport numpy as np

arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[5.36979791 6.23968487 7.01067277]
 [6.08733072 8.31984563 9.64488759]
 [5.78734562 9.46977214 5.74098149]
 [8.64747739 5.44862901 6.79842436]
 [7.21502772 5.5146358  7.58699327]]


In [18]:
#How to print only 3 decimal places in python numpy array?

#Q. Print or show only 3 decimal places of the numpy array rand_arr.

#Input:

#rand_arr = np.random.random((5,3))
import numpy as np
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
print(rand_arr[:4])

[[0.461 0.045 0.595]
 [0.459 0.389 0.265]
 [0.815 0.282 0.339]
 [0.129 0.985 0.367]]


In [19]:

#How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

#Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

#Input:

# Create the random array
#np.random.seed(100)
#rand_arr = np.random.random([3,3])/1e3
#rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]]
# Reset printoptions to default

np.set_printoptions(suppress=False)

# Create the random array

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


In [20]:

#How to limit the number of items printed in output of numpy array?

#Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
#Input:

#a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]
