#  1.How to get the common items between two python numpy arrays?
* Q. Get the common items between a and b
* Input:
* a = np.array([1,2,3,2,3,4,3,4,5,6])
* b = np.array([7,2,10,2,7,4,9,4,9,8])

In [1]:
import numpy as np
# create 2 arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# use the np.intersect1d method
c = np.intersect1d(a, b)
print(c)

[2 4]


# 2. How to remove from one array those items that exist in another?
* Q. From array a remove all items present in array b
* Input:
* a = np.array([1,2,3,4,5])
* b = np.array([5,6,7,8,9])

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


# 3.How to get the positions where elements of two arrays match?
* Q. Get the positions where elements of a and b match
* Input:
* a = np.array([1,2,3,2,3,4,3,4,5,6])
* b = np.array([7,2,10,2,7,4,9,4,9,8])

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


# 4.How to extract all numbers between a given range from a numpy array?
* Q. Get all items between 5 and 10 from a.
* Input:
* a = np.array([2, 6, 1, 9, 10, 3, 27])

In [4]:
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 5  6  7  8  9 10]


# 5.How to make a python function that handles scalars to work on numpy arrays?
* Q. Convert the function maxx that works on two scalars, to work on two arrays.
* Input:
* def maxx(x, y): """Get the maximum of two items""" if x >= y:
* return x *else:
* return y
* maxx(1, 5) #> 5

In [5]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


# 6. How to swap two columns in a 2d numpy array?¶
* Q. Swap columns 1 and 2 in the array arr.
* arr = np.arange(9).reshape(3,3)
* arr
* Show Solution
* Input
* arr = np.arange(9).reshape(3,3)
* arr

In [6]:
arr = np.arange(9).reshape(3,3)
arr
print(arr[:, [1,0,2]])

[[1 0 2]
 [4 3 5]
 [7 6 8]]


# 7.How to swap two rows in a 2d numpy array?¶
* Q. Swap rows 1 and 2 in the array arr:
* arr = np.arange(9).reshape(3,3)
* arr
* Show Solution
* Input
* arr = np.arange(9).reshape(3,3)

In [7]:
arr = np.arange(9).reshape(3,3)
print(arr[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


# 8. How to reverse the rows of a 2D array?
* Q. Reverse the rows of a 2D array arr.
* Input
* arr = np.arange(9).reshape(3,3)
* Show Solution
* Input
* arr = np.arange(9).reshape(3,3)

In [8]:
arr = np.arange(9).reshape(3,3)
print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


# 9. How to reverse the columns of a 2D array?
* Q. Reverse the columns of a 2D array arr.
* Input
* arr = np.arange(9).reshape(3,3)
* Show Solution
* Input
* arr = np.arange(9).reshape(3,3)

In [9]:
arr = np.arange(9).reshape(3,3)
print(arr[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


# 10. How to create a 2D array containing random floats between 5 and 10?
* Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
* Show Solution
* Input
* arr = np.arange(9).reshape(3,3)

In [10]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[7.51439658 5.70736145 7.95087595]
 [8.70766668 8.83546944 9.2379843 ]
 [8.85457145 5.15224114 8.22797481]
 [5.56145876 6.51053357 9.9582221 ]
 [7.2436776  8.44481452 9.50381813]]
