In [110]:
#Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
print(np.all(x))
x = np.array([0, 1, 2, 3])
print(x)
print(np.all(x))

[1 2 3 4]
True
[0 1 2 3]
False


In [148]:
#Write a NumPy program to test whether any of the elements of a given array is non-zero
x = np.array([1, 0, 0, 0])
print(x)
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(x)
print(np.any(x))

[1 0 0 0]
True
[0 0 0 0]
False


In [112]:
#Create an identity matrix of dimension 4-by-4
x = np. zeros((4, 4))
x[::2, 1::2] = 1.
x[1::2, ::2] = 1.
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [113]:
#Convert a 1-D array to a 3-D array
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [114]:
#Convert all the elements of a numpy array from float to integer datatype
ar = np.reshape(ar, (2, 2, 3))
print('3D Numpy array:')
print(ar)

3D Numpy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [115]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.80894327 0.92259336 0.1232722  0.02355592 0.61598343 0.1989646
  0.11605297 0.73963817 0.27719075 0.56129058]
 [0.70910596 0.03624982 0.27718258 0.68937075 0.84725484 0.02100025
  0.22120142 0.64419506 0.0891497  0.66162126]
 [0.41986117 0.52196025 0.02563716 0.3814739  0.60933385 0.58167915
  0.58312265 0.45553685 0.8444529  0.74963239]
 [0.44992464 0.85177442 0.45777929 0.36256338 0.66127737 0.63039161
  0.35602853 0.93096158 0.9331481  0.47741258]
 [0.89805468 0.18356275 0.44471699 0.91819806 0.47349605 0.89045475
  0.26057035 0.15970916 0.83741818 0.35383315]
 [0.93403798 0.43633677 0.99476242 0.42445363 0.62748088 0.37262003
  0.09036595 0.03701453 0.48625736 0.66484342]
 [0.07620233 0.81539927 0.82393211 0.06639622 0.14554203 0.4054931
  0.21316591 0.93224121 0.94890249 0.31774924]
 [0.83855705 0.26015657 0.59475186 0.08687023 0.48117632 0.46530395
  0.41672422 0.74953933 0.74850379 0.98326198]
 [0.70051167 0.16594042 0.44431461 0.72250409 0.41420086 0.13721772
  0.87886275 0

In [116]:
#Create a random vector of size 30 and find the mean value
x = np.random.random(30)
m = x.mean()
print (m)

0.45052640723050613


In [117]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = np.diag(1+np.arange(4), k = -1)
print (y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [118]:
#Create a 2d array with 1 on the border and 0 inside
x = np.ones((6,6))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [119]:
#How to add a border (filled with 0's) around an existing array?
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [120]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
y = np.zeros ((8,8), dtype=int)
y[1::2, ::2]= 1
y[::2, 1::2] = 1
print (y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [121]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [122]:
#Create a checkerboard 8x8 matrix using the tile function
array= np.array([[0,1], [1,0]])
S = np.tile(array,(4,4))
print (S)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [123]:
#Normalize a 5x5 random matrix
i = np.random.random((5,5))
imax, imin = i.max(), i.min()
i= (i-imin)/(imax-imin)
print (i)

[[1.         0.17822805 0.24261872 0.0207932  0.27176678]
 [0.52332401 0.89530499 0.53964073 0.48959297 0.94406375]
 [0.62458868 0.43863554 0.25719735 0.99481379 0.51089024]
 [0.9763577  0.51840413 0.1004395  0.33328847 0.60210554]
 [0.85910675 0.7607199  0.         0.37052561 0.23294484]]


In [124]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-124-6826c9df19bf>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [125]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
r= np.dot(np.ones((5,3)), np.ones((3,2)))
print (r)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [126]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [128]:
#How to round away from zero a float array ?
x = np.random.uniform(-5, +5, 5)
print(np.copysign(np.ceil(np.abs(x)), x))


[-5.  4. -2.  2. -5.]


In [129]:
#How to find common values between two arrays?
x = np.arange(0, 20)
y = np.arange(5, 15)
print(np.intersect1d(x, y))

[ 5  6  7  8  9 10 11 12 13 14]


In [130]:
#How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2021-08-16
Today:  2021-08-17
Tomorrow:  2021-08-18


In [131]:
##How to get all the dates corresponding to the month of July 2016?
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [132]:
#How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(5) * 1
B = np.ones(5) * 2
C = np.ones(5) * 3
print(np.add(A, B, out=B))
print(np.divide(A, 2, out=A))
print(np.negative(A, out=A))
print(np.multiply(A, B, out=A))

[3. 3. 3. 3. 3.]
[0.5 0.5 0.5 0.5 0.5]
[-0.5 -0.5 -0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5 -1.5 -1.5]


In [133]:
#Extract the integer part of a random array of positive numbers using 4 different methods
i = np.random.uniform(0,10,10)

print(i - i%1)
print(i // 1)
print(np.floor(i))
print(i.astype(int))
print(np.trunc(i))

[3. 1. 8. 1. 2. 7. 4. 1. 1. 3.]
[3. 1. 8. 1. 2. 7. 4. 1. 1. 3.]
[3. 1. 8. 1. 2. 7. 4. 1. 1. 3.]
[3 1 8 1 2 7 4 1 1 3]
[3. 1. 8. 1. 2. 7. 4. 1. 1. 3.]


In [134]:
#Create a 5x5 matrix with row values ranging from 0 to 4
s = np.zeros((5,5))
s += np.arange(5)
print(Z)



[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [135]:
#Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [136]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [137]:
#Create a random vector of size 10 and sort it
n = np.random.random(10)
n.sort()
print(n)

[0.04855083 0.12727512 0.38399931 0.40575354 0.43137251 0.43905692
 0.45537637 0.54564448 0.66348042 0.85561231]


In [138]:
#How to sum a small array faster than np.sum?
x = np.arange(10)
np.add.reduce(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [139]:
#Consider two random array A and B, check if they are equal
A = np.random.randint(0,1,4)
B = np.random.randint(0,1,4)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

True
True


In [140]:
##Make an array immutable (read-only)
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [141]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
s = np.sqrt(x ** 2 + y ** 2)
a = np.arctan2(y, x)
print(s)
print(a)

[0.71058198 0.96919922 0.2078396  0.48326996 0.83878342 1.00531869
 0.75730391 0.42406137 1.10767552 0.37088142]
[0.24875451 1.15801415 0.85866543 0.89982222 1.07775773 1.44559221
 1.35008679 1.20614337 0.78022571 1.25119993]


In [142]:
#Create random vector of size 10 and replace the maximum value by 0
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.19255234 0.57926718 0.61076063 0.33309024 0.43546202 0.7156025
 0.14719272 0.35780006 0.         0.80124776]


In [143]:
##Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
p = np.zeros((5,5), [('x',float),('y',float)])
p['x'], p['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(p)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [144]:
#Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [145]:
#Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
p = np.arange(8)
q = p + 0.5
r = 1.0 / np.subtract.outer(p, q)
print(np.linalg.det(r))

3638.1636371179666


In [146]:
##Create a structured array representing a position (x,y) and a color (r,g,b)
ss = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(ss)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-146-2adfd3e7582c>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ss = np.zeros(10, [ ('position', [ ('x', float, 1),
